kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: simplilearnproject-hpa
spec:
  targetCPUUtilizationPercentage: 40
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simplilearnproject
