---
apiVersion: v1
kind: Service
metadata:
  name: simplilearnproject
  namespace: simplilearn-namespace
spec:
  type: LoadBalancer
  selector:
    app: simplilearnproject
  ports:
  - port: 80
    targetPort: 3000
