kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: get-pods
rules:
 - apiGroups: ["*"]
   resources: ["pods"]
   verbs: ["create","update","list","get","delete"]
 - apiGroups: ["extensions","apps"]
   resources: ["deployments"]
   verbs: ["get","list","create","update","delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: simplilearn-get-pods
subjects:
- apiGroup: ""
 kind: User
 name: simplilearn
roleRef:
 apiGroup: ""
 kind: Role
 name: get-pods
